/* ===================== 한국OH! Content Data ===================== */

const ACHIEVEMENTS = [
  { id: "first_steps", icon: "🏆", name: "First Steps", desc: "Complete your first lesson", check: (s) => s.lessonsCompleted.length >= 1 },
  { id: "streak_7", icon: "🔥", name: "7-Day Learner", desc: "Maintain a 7-day streak", check: (s) => s.streak >= 7 },
  { id: "word_collector", icon: "📖", name: "Word Collector", desc: "Learn 100 Korean words", check: (s) => Object.keys(s.vocabProgress).length >= 100 },
  { id: "good_listener", icon: "🎧", name: "Good Listener", desc: "Complete 20 listening exercises", check: (s) => s.listeningDone >= 20 },
  { id: "topik_challenger", icon: "✍️", name: "TOPIK Challenger", desc: "Complete your first TOPIK practice set", check: (s) => s.topikSetsCompleted >= 1 },
  { id: "level_5", icon: "⭐", name: "Rising Star", desc: "Reach Level 5", check: (s) => levelFromXP(s.xp).level >= 5 },
  { id: "grammar_5", icon: "📐", name: "Grammar Geek", desc: "Complete 5 grammar topics", check: (s) => s.grammarCompleted.length >= 5 },
  { id: "perfect_lesson", icon: "💯", name: "Perfectionist", desc: "Finish a lesson with 100% accuracy", check: (s) => s.perfectLessons >= 1 },
];

/* Vocabulary bank: word, romanization, meaning, example, category */
const VOCAB = [
  { id: "v1", ko: "학교", rom: "hakgyo", en: "school", ex: "저는 학교에 가요.", exEn: "I go to school.", cat: "Places" },
  { id: "v2", ko: "안녕하세요", rom: "annyeonghaseyo", en: "hello", ex: "안녕하세요, 만나서 반가워요!", exEn: "Hello, nice to meet you!", cat: "Greetings" },
  { id: "v3", ko: "감사합니다", rom: "gamsahamnida", en: "thank you", ex: "도와주셔서 감사합니다.", exEn: "Thank you for helping me.", cat: "Greetings" },
  { id: "v4", ko: "물", rom: "mul", en: "water", ex: "물 좀 주세요.", exEn: "Please give me some water.", cat: "Food" },
  { id: "v5", ko: "밥", rom: "bap", en: "rice / meal", ex: "밥을 먹었어요.", exEn: "I ate a meal.", cat: "Food" },
  { id: "v6", ko: "친구", rom: "chingu", en: "friend", ex: "친구랑 같이 가요.", exEn: "I go together with a friend.", cat: "People" },
  { id: "v7", ko: "사람", rom: "saram", en: "person", ex: "저 사람은 누구예요?", exEn: "Who is that person?", cat: "People" },
  { id: "v8", ko: "하나", rom: "hana", en: "one (native)", ex: "사과 하나 주세요.", exEn: "Give me one apple.", cat: "Numbers" },
  { id: "v9", ko: "둘", rom: "dul", en: "two (native)", ex: "사과 둘이 있습니다.", exEn: "There are two apples.", cat: "Numbers" },
  { id: "v10", ko: "집", rom: "jip", en: "house / home", ex: "저는 집에 있어요.", exEn: "I am at home.", cat: "Places" },
  { id: "v11", ko: "오늘", rom: "oneul", en: "today", ex: "오늘은 월요일이에요.", exEn: "Today is Monday.", cat: "Time" },
  { id: "v12", ko: "내일", rom: "naeil", en: "tomorrow", ex: "내일 만나요.", exEn: "See you tomorrow.", cat: "Time" },
  { id: "v13", ko: "먹다", rom: "meokda", en: "to eat", ex: "저는 사과를 먹어요.", exEn: "I eat an apple.", cat: "Verbs" },
  { id: "v14", ko: "가다", rom: "gada", en: "to go", ex: "학교에 가요.", exEn: "I go to school.", cat: "Verbs" },
  { id: "v15", ko: "좋다", rom: "jota", en: "to be good", ex: "날씨가 좋아요.", exEn: "The weather is good.", cat: "Adjectives" },
  { id: "v16", ko: "이름", rom: "ireum", en: "name", ex: "제 이름은 민수예요.", exEn: "My name is Minsu.", cat: "People" },
  { id: "v17", ko: "시간", rom: "sigan", en: "time", ex: "시간이 없어요.", exEn: "I don't have time.", cat: "Time" },
  { id: "v18", ko: "돈", rom: "don", en: "money", ex: "돈이 조금 있어요.", exEn: "I have a little money.", cat: "Objects" },
  { id: "v19", ko: "책", rom: "chaek", en: "book", ex: "저는 책을 읽어요.", exEn: "I read a book.", cat: "Objects" },
  { id: "v20", ko: "커피", rom: "keopi", en: "coffee", ex: "커피 한 잔 주세요.", exEn: "One cup of coffee, please.", cat: "Food" },

  /* Additional Vocabulary */
  { id: "v21", ko: "사과", rom: "sagwa", en: "apple", ex: "사과를 먹어요.", exEn: "I eat an apple.", cat: "Food" },
  { id: "v22", ko: "셋", rom: "set", en: "three (native)", ex: "고양이 셋이 있습니다.", exEn: "There are three cats.", cat: "Numbers" },
  { id: "v23", ko: "식당", rom: "sikdang", en: "restaurant", ex: "식당에서 밥을 먹어요.", exEn: "I eat at a restaurant.", cat: "Places" },
  { id: "v24", ko: "공원", rom: "gongwon", en: "park", ex: "공원에서 운동해요.", exEn: "I exercise at the park.", cat: "Places" },
  { id: "v25", ko: "도서관", rom: "doseogwan", en: "library", ex: "도서관에서 책을 읽어요.", exEn: "I read a book at the library.", cat: "Places" },
  { id: "v26", ko: "병원", rom: "byeongwon", en: "hospital", ex: "병원에 가요.", exEn: "I go to the hospital.", cat: "Places" },
  { id: "v27", ko: "시장", rom: "sijang", en: "market", ex: "시장에서 과일을 사요.", exEn: "I buy fruit at the market.", cat: "Places" },
  { id: "v28", ko: "가족", rom: "gajok", en: "family", ex: "우리 가족은 네 명이에요.", exEn: "There are four people in my family.", cat: "People" },
  { id: "v29", ko: "선생님", rom: "seonsaengnim", en: "teacher", ex: "선생님께 질문해요.", exEn: "I ask the teacher a question.", cat: "People" },
  { id: "v30", ko: "학생", rom: "haksaeng", en: "student", ex: "저는 학생이에요.", exEn: "I am a student.", cat: "People" },
  { id: "v31", ko: "한국", rom: "hanguk", en: "Korea", ex: "저는 한국에 가고 싶어요.", exEn: "I want to go to Korea.", cat: "Places" },
  { id: "v32", ko: "한국어", rom: "hangugeo", en: "Korean language", ex: "한국어를 공부해요.", exEn: "I study Korean.", cat: "Language" },
  { id: "v33", ko: "공부하다", rom: "gongbuhada", en: "to study", ex: "매일 한국어를 공부해요.", exEn: "I study Korean every day.", cat: "Verbs" },
  { id: "v34", ko: "읽다", rom: "ikda", en: "to read", ex: "책을 읽어요.", exEn: "I read a book.", cat: "Verbs" },
  { id: "v35", ko: "마시다", rom: "masida", en: "to drink", ex: "물을 마셔요.", exEn: "I drink water.", cat: "Verbs" },
  { id: "v36", ko: "보다", rom: "boda", en: "to see / watch", ex: "영화를 봐요.", exEn: "I watch a movie.", cat: "Verbs" },
  { id: "v37", ko: "듣다", rom: "deutda", en: "to listen / hear", ex: "음악을 들어요.", exEn: "I listen to music.", cat: "Verbs" },
  { id: "v38", ko: "만나다", rom: "mannada", en: "to meet", ex: "친구를 만나요.", exEn: "I meet a friend.", cat: "Verbs" },
  { id: "v39", ko: "자다", rom: "jada", en: "to sleep", ex: "밤에 자요.", exEn: "I sleep at night.", cat: "Verbs" },
  { id: "v40", ko: "일어나다", rom: "ireonada", en: "to get up", ex: "아침에 일어나요.", exEn: "I get up in the morning.", cat: "Verbs" },
  { id: "v41", ko: "빠르다", rom: "ppareuda", en: "to be fast", ex: "기차가 빨라요.", exEn: "The train is fast.", cat: "Adjectives" },
  { id: "v42", ko: "느리다", rom: "neurida", en: "to be slow", ex: "인터넷이 느려요.", exEn: "The internet is slow.", cat: "Adjectives" },
  { id: "v43", ko: "크다", rom: "keuda", en: "to be big", ex: "집이 커요.", exEn: "The house is big.", cat: "Adjectives" },
  { id: "v44", ko: "작다", rom: "jakda", en: "to be small", ex: "방이 작아요.", exEn: "The room is small.", cat: "Adjectives" },
  { id: "v45", ko: "예쁘다", rom: "yeppeuda", en: "to be pretty", ex: "꽃이 예뻐요.", exEn: "The flower is pretty.", cat: "Adjectives" },
  { id: "v46", ko: "맛있다", rom: "masitda", en: "to be delicious", ex: "김치가 맛있어요.", exEn: "The kimchi is delicious.", cat: "Adjectives" },
  { id: "v47", ko: "어제", rom: "eoje", en: "yesterday", ex: "어제는 비가 왔어요.", exEn: "It rained yesterday.", cat: "Time" },
  { id: "v48", ko: "지금", rom: "jigeum", en: "now", ex: "지금 뭐 해요?", exEn: "What are you doing now?", cat: "Time" },
  { id: "v49", ko: "아침", rom: "achim", en: "morning", ex: "아침에 일어나요.", exEn: "I get up in the morning.", cat: "Time" },
  { id: "v50", ko: "저녁", rom: "jeonyeok", en: "evening / dinner", ex: "저녁에 친구를 만나요.", exEn: "I meet my friend in the evening.", cat: "Time" },
  { id: "v51", ko: "주말", rom: "jumal", en: "weekend", ex: "주말에 쉬어요.", exEn: "I rest on the weekend.", cat: "Time" },
  { id: "v52", ko: "월요일", rom: "woryoil", en: "Monday", ex: "월요일에 학교에 가요.", exEn: "I go to school on Monday.", cat: "Time" },
  { id: "v53", ko: "날씨", rom: "nalssi", en: "weather", ex: "오늘 날씨가 좋아요.", exEn: "The weather is good today.", cat: "Nature" },
  { id: "v54", ko: "비", rom: "bi", en: "rain", ex: "비가 와요.", exEn: "It is raining.", cat: "Nature" },
  { id: "v55", ko: "눈", rom: "nun", en: "snow", ex: "겨울에 눈이 와요.", exEn: "It snows in winter.", cat: "Nature" },
  { id: "v56", ko: "음악", rom: "eumak", en: "music", ex: "음악을 들어요.", exEn: "I listen to music.", cat: "Entertainment" },
  { id: "v57", ko: "영화", rom: "yeonghwa", en: "movie", ex: "주말에 영화를 봐요.", exEn: "I watch a movie on the weekend.", cat: "Entertainment" },
  { id: "v58", ko: "운동", rom: "undong", en: "exercise", ex: "매일 운동을 해요.", exEn: "I exercise every day.", cat: "Activities" },
  { id: "v59", ko: "여행", rom: "yeohaeng", en: "travel / trip", ex: "한국으로 여행을 가요.", exEn: "I travel to Korea.", cat: "Activities" },
  { id: "v60", ko: "사진", rom: "sajin", en: "photo", ex: "사진을 찍어요.", exEn: "I take a photo.", cat: "Objects" },
  { id: "v61", ko: "영어", rom: "yeongeo", en: "English language", ex: "영어 공부하고 있어요.", exEn: "I am learning English.", cat: "Language" },
  { id: "v62", ko: "은행", rom: "eunhaeng", en: "bank", ex: "은행에 가요.", exEn: "I go to the bank.", cat: "Places" },
  { id: "v63", ko: "우체국", rom: "ucheguk", en: "post office", ex: "우체국에서 편지를 보내요.", exEn: "I send a letter at the post office.", cat: "Places" },
  { id: "v64", ko: "공항", rom: "gonghang", en: "airport", ex: "공항에 도착했어요.", exEn: "I arrived at the airport.", cat: "Places" },
  { id: "v65", ko: "역", rom: "yeok", en: "station", ex: "역에서 친구를 만나요.", exEn: "I meet my friend at the station.", cat: "Places" },
  { id: "v66", ko: "카페", rom: "kape", en: "cafe", ex: "카페에서 커피를 마셔요.", exEn: "I drink coffee at a cafe.", cat: "Places" },
  { id: "v67", ko: "마트", rom: "mateu", en: "supermarket", ex: "마트에서 장을 봐요.", exEn: "I shop for groceries at the supermarket.", cat: "Places" },
  { id: "v68", ko: "서점", rom: "seojeom", en: "bookstore", ex: "서점에서 책을 사요.", exEn: "I buy a book at the bookstore.", cat: "Places" },
  { id: "v69", ko: "박물관", rom: "bangmulgwan", en: "museum", ex: "박물관을 구경해요.", exEn: "I look around the museum.", cat: "Places" },
  { id: "v70", ko: "극장", rom: "geukjang", en: "theater", ex: "극장에서 영화를 봐요.", exEn: "I watch a movie at the theater.", cat: "Places" },
  { id: "v71", ko: "호텔", rom: "hotel", en: "hotel", ex: "호텔에서 쉬어요.", exEn: "I rest at the hotel.", cat: "Places" },
  { id: "v72", ko: "안녕", rom: "annyeong", en: "hi / bye", ex: "안녕! 잘 지냈어?", exEn: "Hi! How have you been?", cat: "Greetings" },
  { id: "v73", ko: "반갑습니다", rom: "bangapseumnida", en: "nice to meet you", ex: "만나서 반갑습니다.", exEn: "Nice to meet you.", cat: "Greetings" },
  { id: "v74", ko: "반가워요", rom: "bangawoyo", en: "nice to meet you", ex: "만나서 반가워요.", exEn: "Nice to meet you.", cat: "Greetings" },
  { id: "v75", ko: "죄송합니다", rom: "joesonghamnida", en: "I'm sorry", ex: "늦어서 죄송합니다.", exEn: "I'm sorry for being late.", cat: "Greetings" },
  { id: "v76", ko: "미안해요", rom: "mianhaeyo", en: "sorry", ex: "미안해요. 제가 잘못했어요.", exEn: "Sorry. I made a mistake.", cat: "Greetings" },
  { id: "v77", ko: "괜찮아요", rom: "gwaenchanayo", en: "it's okay", ex: "괜찮아요. 걱정하지 마세요.", exEn: "It's okay. Don't worry.", cat: "Greetings" },
  { id: "v78", ko: "어서 오세요", rom: "eoseo oseyo", en: "welcome", ex: "어서 오세요!", exEn: "Welcome!", cat: "Greetings" },
  { id: "v79", ko: "잘 지냈어요?", rom: "jal jinaesseoyo", en: "how have you been?", ex: "오랜만이에요. 잘 지냈어요?", exEn: "Long time no see. How have you been?", cat: "Greetings" },
  { id: "v80", ko: "잘 가요", rom: "jal gayo", en: "goodbye", ex: "내일 봐요. 잘 가요!", exEn: "See you tomorrow. Goodbye!", cat: "Greetings" },
  { id: "v81", ko: "잘 자요", rom: "jal jayo", en: "good night", ex: "늦었어요. 잘 자요.", exEn: "It's late. Good night.", cat: "Greetings" },
  { id: "v82", ko: "또 만나요", rom: "tto mannayo", en: "see you again", ex: "다음 주에 또 만나요.", exEn: "See you again next week.", cat: "Greetings" },
  { id: "v83", ko: "실례합니다", rom: "sillyehamnida", en: "excuse me", ex: "실례합니다. 질문이 있어요.", exEn: "Excuse me. I have a question.", cat: "Greetings" },
  { id: "v84", ko: "축하합니다", rom: "chukhahamnida", en: "congratulations", ex: "졸업을 축하합니다.", exEn: "Congratulations on your graduation.", cat: "Greetings" },
  { id: "v85", ko: "좋은 아침이에요", rom: "joeun achimieyo", en: "good morning", ex: "좋은 아침이에요!", exEn: "Good morning!", cat: "Greetings" },
  { id: "v86", ko: "수고하세요", rom: "sugohaseyo", en: "have a good day / keep up the good work", ex: "먼저 갈게요. 수고하세요.", exEn: "I'll go first. Have a good day.", cat: "Greetings" },
  { id: "v87", ko: "다녀오세요", rom: "danyeooseyo", en: "see you when you get back", ex: "잘 다녀오세요.", exEn: "See you when you get back.", cat: "Greetings" },
  { id: "v88", ko: "다녀왔어요", rom: "danyeowasseoyo", en: "I'm back", ex: "학교에서 다녀왔어요.", exEn: "I'm back from school.", cat: "Greetings" },
  { id: "v89", ko: "잘 부탁드립니다", rom: "jal butakdeurimnida", en: "I look forward to working with you", ex: "앞으로 잘 부탁드립니다.", exEn: "I look forward to working with you.", cat: "Greetings" },
  { id: "v91", ko: "김치", rom: "gimchi", en: "kimchi", ex: "김치를 먹어요.", exEn: "I eat kimchi.", cat: "Food" },
  { id: "v92", ko: "라면", rom: "ramyeon", en: "ramen", ex: "라면을 끓여요.", exEn: "I cook ramen.", cat: "Food" },
  { id: "v93", ko: "고기", rom: "gogi", en: "meat", ex: "고기를 좋아해요.", exEn: "I like meat.", cat: "Food" },
  { id: "v94", ko: "생선", rom: "saengseon", en: "fish", ex: "생선을 먹어요.", exEn: "I eat fish.", cat: "Food" },
  { id: "v95", ko: "과일", rom: "gwail", en: "fruit", ex: "과일을 많이 먹어요.", exEn: "I eat a lot of fruit.", cat: "Food" },
  { id: "v96", ko: "빵", rom: "ppang", en: "bread", ex: "아침에 빵을 먹어요.", exEn: "I eat bread in the morning.", cat: "Food" },
  { id: "v97", ko: "우유", rom: "uyu", en: "milk", ex: "우유를 마셔요.", exEn: "I drink milk.", cat: "Food" },
  { id: "v98", ko: "주스", rom: "juseu", en: "juice", ex: "오렌지 주스를 마셔요.", exEn: "I drink orange juice.", cat: "Food" },
  { id: "v99", ko: "김밥", rom: "gimbap", en: "gimbap", ex: "김밥을 먹고 싶어요.", exEn: "I want to eat gimbap.", cat: "Food" },
  { id: "v100", ko: "떡", rom: "tteok", en: "rice cake", ex: "떡을 먹어요.", exEn: "I eat rice cakes.", cat: "Food" },
  { id: "v101", ko: "국", rom: "guk", en: "soup", ex: "따뜻한 국을 먹어요.", exEn: "I eat warm soup.", cat: "Food" },
  { id: "v102", ko: "채소", rom: "chaeso", en: "vegetables", ex: "채소를 많이 먹어요.", exEn: "I eat lots of vegetables.", cat: "Food" },
  { id: "v103", ko: "고추", rom: "gochu", en: "chili pepper", ex: "고추가 매워요.", exEn: "The chili pepper is spicy.", cat: "Food" },
  { id: "v104", ko: "설탕", rom: "seoltang", en: "sugar", ex: "커피에 설탕을 넣어요.", exEn: "I put sugar in my coffee.", cat: "Food" },
  { id: "v105", ko: "소금", rom: "sogeum", en: "salt", ex: "음식에 소금을 넣어요.", exEn: "I add salt to the food.", cat: "Food" },
  { id: "v106", ko: "어머니", rom: "eomeoni", en: "mother", ex: "어머니와 함께 살아요.", exEn: "I live with my mother.", cat: "People" },
  { id: "v107", ko: "아버지", rom: "abeoji", en: "father", ex: "아버지는 회사원이에요.", exEn: "My father is an office worker.", cat: "People" },
  { id: "v108", ko: "형", rom: "hyeong", en: "older brother (male speaker)", ex: "형과 영화를 봐요.", exEn: "I watch a movie with my older brother.", cat: "People" },
  { id: "v109", ko: "누나", rom: "nuna", en: "older sister (male speaker)", ex: "누나는 학생이에요.", exEn: "My older sister is a student.", cat: "People" },
  { id: "v110", ko: "오빠", rom: "oppa", en: "older brother (female speaker)", ex: "오빠와 쇼핑해요.", exEn: "I shop with my older brother.", cat: "People" },
  { id: "v111", ko: "언니", rom: "eonni", en: "older sister (female speaker)", ex: "언니가 요리를 해요.", exEn: "My older sister cooks.", cat: "People" },
  { id: "v112", ko: "동생", rom: "dongsaeng", en: "younger sibling", ex: "동생과 놀아요.", exEn: "I play with my younger sibling.", cat: "People" },
  { id: "v113", ko: "아이", rom: "ai", en: "child", ex: "아이가 웃어요.", exEn: "The child is laughing.", cat: "People" },
  { id: "v114", ko: "남자", rom: "namja", en: "man", ex: "저 남자는 선생님이에요.", exEn: "That man is a teacher.", cat: "People" },
  { id: "v115", ko: "여자", rom: "yeoja", en: "woman", ex: "저 여자는 의사예요.", exEn: "That woman is a doctor.", cat: "People" },
  { id: "v116", ko: "의사", rom: "uisa", en: "doctor", ex: "의사에게 질문해요.", exEn: "I ask the doctor a question.", cat: "People" },
  { id: "v117", ko: "회사원", rom: "hoesawon", en: "office worker", ex: "저는 회사원이에요.", exEn: "I am an office worker.", cat: "People" },
  { id: "v118", ko: "손님", rom: "sonnim", en: "customer / guest", ex: "손님이 많아요.", exEn: "There are many customers.", cat: "People" },
  { id: "v119", ko: "친척", rom: "chincheok", en: "relative", ex: "주말에 친척을 만나요.", exEn: "I meet relatives on the weekend.", cat: "People" },
  { id: "v120", ko: "넷", rom: "net", en: "four (native)", ex: "사과 넷 주세요.", exEn: "Please give me four apples.", cat: "Numbers" },
  { id: "v121", ko: "다섯", rom: "daseot", en: "five (native)", ex: "학생 다섯 명이 있어요.", exEn: "There are five students.", cat: "Numbers" },
  { id: "v122", ko: "여섯", rom: "yeoseot", en: "six (native)", ex: "사과 여섯 개가 있어요.", exEn: "There are six apples.", cat: "Numbers" },
  { id: "v123", ko: "일곱", rom: "ilgop", en: "seven (native)", ex: "일곱 명이 왔어요.", exEn: "Seven people came.", cat: "Numbers" },
  { id: "v124", ko: "여덟", rom: "yeodeol", en: "eight (native)", ex: "여덟 개 주세요.", exEn: "Please give me eight.", cat: "Numbers" },
  { id: "v125", ko: "아홉", rom: "ahop", en: "nine (native)", ex: "아홉 명이 있어요.", exEn: "There are nine people.", cat: "Numbers" },
  { id: "v126", ko: "열", rom: "yeol", en: "ten (native)", ex: "열 개 있어요.", exEn: "There are ten.", cat: "Numbers" },
  { id: "v127", ko: "스물", rom: "seumul", en: "twenty (native)", ex: "스무 살이에요.", exEn: "I am twenty years old.", cat: "Numbers" },
  { id: "v128", ko: "일", rom: "il", en: "one (Sino-Korean)", ex: "일 번을 선택하세요.", exEn: "Choose number one.", cat: "Numbers" },
  { id: "v129", ko: "이", rom: "i", en: "two (Sino-Korean)", ex: "이 층에 있어요.", exEn: "It is on the second floor.", cat: "Numbers" },
  { id: "v130", ko: "삼", rom: "sam", en: "three (Sino-Korean)", ex: "삼 분 기다려 주세요.", exEn: "Please wait three minutes.", cat: "Numbers" },
  { id: "v131", ko: "사", rom: "sa", en: "four (Sino-Korean)", ex: "사 번 문제예요.", exEn: "It is question number four.", cat: "Numbers" },
  { id: "v132", ko: "오", rom: "o", en: "five (Sino-Korean)", ex: "오 월이에요.", exEn: "It is May.", cat: "Numbers" },
  { id: "v133", ko: "육", rom: "yuk", en: "six (Sino-Korean)", ex: "육 시에 만나요.", exEn: "Let's meet at six.", cat: "Numbers" },
  { id: "v134", ko: "칠", rom: "chil", en: "seven (Sino-Korean)", ex: "칠 월에 여행해요.", exEn: "I travel in July.", cat: "Numbers" },
  { id: "v135", ko: "팔", rom: "pal", en: "eight (Sino-Korean)", ex: "팔 번 버스를 타요.", exEn: "I take bus number eight.", cat: "Numbers" },
  { id: "v136", ko: "구", rom: "gu", en: "nine (Sino-Korean)", ex: "구 월에 시작해요.", exEn: "It starts in September.", cat: "Numbers" },
  { id: "v137", ko: "새벽", rom: "saebyeok", en: "dawn / early morning", ex: "새벽에 일어나요.", exEn: "I wake up at dawn.", cat: "Time" },
  { id: "v138", ko: "오전", rom: "ojeon", en: "morning / AM", ex: "오전에 수업이 있어요.", exEn: "I have class in the morning.", cat: "Time" },
  { id: "v139", ko: "오후", rom: "ohu", en: "afternoon / PM", ex: "오후에 만나요.", exEn: "Let's meet in the afternoon.", cat: "Time" },
  { id: "v140", ko: "밤", rom: "bam", en: "night", ex: "밤에 책을 읽어요.", exEn: "I read a book at night.", cat: "Time" },
  { id: "v141", ko: "주", rom: "ju", en: "week", ex: "일주일은 칠 일이에요.", exEn: "A week has seven days.", cat: "Time" },
  { id: "v142", ko: "달", rom: "dal", en: "month", ex: "한 달 동안 공부했어요.", exEn: "I studied for one month.", cat: "Time" },
  { id: "v143", ko: "년", rom: "nyeon", en: "year", ex: "일 년 동안 한국어를 공부했어요.", exEn: "I studied Korean for one year.", cat: "Time" },
  { id: "v144", ko: "요일", rom: "yoil", en: "day of the week", ex: "오늘은 무슨 요일이에요?", exEn: "What day of the week is today?", cat: "Time" },
  { id: "v145", ko: "휴일", rom: "hyuil", en: "holiday", ex: "휴일에는 집에서 쉬어요.", exEn: "I rest at home on holidays.", cat: "Time" },
  { id: "v146", ko: "평일", rom: "pyeongil", en: "weekday", ex: "평일에는 바빠요.", exEn: "I am busy on weekdays.", cat: "Time" },
  { id: "v147", ko: "나중", rom: "najung", en: "later", ex: "나중에 전화할게요.", exEn: "I'll call you later.", cat: "Time" },
  { id: "v148", ko: "먼저", rom: "meonjeo", en: "first / beforehand", ex: "제가 먼저 갈게요.", exEn: "I'll go first.", cat: "Time" },
  { id: "v149", ko: "쓰다", rom: "sseuda", en: "to write / use", ex: "편지를 써요.", exEn: "I write a letter.", cat: "Verbs" },
  { id: "v150", ko: "배우다", rom: "baeuda", en: "to learn", ex: "한국어를 배워요.", exEn: "I learn Korean.", cat: "Verbs" },
  { id: "v151", ko: "일하다", rom: "ilhada", en: "to work", ex: "회사에서 일해요.", exEn: "I work at a company.", cat: "Verbs" },
  { id: "v152", ko: "쉬다", rom: "swida", en: "to rest", ex: "주말에 쉬어요.", exEn: "I rest on the weekend.", cat: "Verbs" },
  { id: "v153", ko: "사다", rom: "sada", en: "to buy", ex: "책을 사요.", exEn: "I buy a book.", cat: "Verbs" },
  { id: "v154", ko: "팔다", rom: "palda", en: "to sell", ex: "가게에서 과일을 팔아요.", exEn: "I sell fruit at the store.", cat: "Verbs" },
  { id: "v155", ko: "만들다", rom: "mandeulda", en: "to make", ex: "김밥을 만들어요.", exEn: "I make gimbap.", cat: "Verbs" },
  { id: "v156", ko: "열다", rom: "yeolda", en: "to open", ex: "문을 열어요.", exEn: "I open the door.", cat: "Verbs" },
  { id: "v157", ko: "닫다", rom: "datda", en: "to close", ex: "창문을 닫아요.", exEn: "I close the window.", cat: "Verbs" },
  { id: "v158", ko: "기다리다", rom: "gidarida", en: "to wait", ex: "친구를 기다려요.", exEn: "I wait for my friend.", cat: "Verbs" },
  { id: "v159", ko: "찾다", rom: "chatda", en: "to find / look for", ex: "열쇠를 찾아요.", exEn: "I look for the key.", cat: "Verbs" },
  { id: "v160", ko: "덥다", rom: "deopda", en: "to be hot", ex: "오늘은 더워요.", exEn: "It is hot today.", cat: "Adjectives" },
  { id: "v161", ko: "춥다", rom: "chupda", en: "to be cold", ex: "겨울에는 추워요.", exEn: "It is cold in winter.", cat: "Adjectives" },
  { id: "v162", ko: "따뜻하다", rom: "ttatteuthada", en: "to be warm", ex: "날씨가 따뜻해요.", exEn: "The weather is warm.", cat: "Adjectives" },
  { id: "v163", ko: "시원하다", rom: "siwonhada", en: "to be cool / refreshing", ex: "바람이 시원해요.", exEn: "The wind is cool.", cat: "Adjectives" },
  { id: "v164", ko: "비싸다", rom: "bissada", en: "to be expensive", ex: "이 가방은 비싸요.", exEn: "This bag is expensive.", cat: "Adjectives" },
  { id: "v165", ko: "싸다", rom: "ssada", en: "to be cheap", ex: "이 책은 싸요.", exEn: "This book is cheap.", cat: "Adjectives" },
  { id: "v166", ko: "어렵다", rom: "eoryeopda", en: "to be difficult", ex: "한국어가 어려워요.", exEn: "Korean is difficult.", cat: "Adjectives" },
  { id: "v167", ko: "쉽다", rom: "swipda", en: "to be easy", ex: "이 문제는 쉬워요.", exEn: "This question is easy.", cat: "Adjectives" },
  { id: "v168", ko: "재미있다", rom: "jaemiitda", en: "to be interesting / fun", ex: "영화가 재미있어요.", exEn: "The movie is interesting.", cat: "Adjectives" },
  { id: "v169", ko: "재미없다", rom: "jaemieopda", en: "to be boring / not fun", ex: "그 영화는 재미없어요.", exEn: "That movie is boring.", cat: "Adjectives" },
  { id: "v170", ko: "바쁘다", rom: "bappeuda", en: "to be busy", ex: "오늘은 바빠요.", exEn: "I am busy today.", cat: "Adjectives" },
  { id: "v171", ko: "한가하다", rom: "hangahada", en: "to be free / not busy", ex: "주말에는 한가해요.", exEn: "I am free on weekends.", cat: "Adjectives" },
  { id: "v172", ko: "피곤하다", rom: "pigonhada", en: "to be tired", ex: "오늘 너무 피곤해요.", exEn: "I am very tired today.", cat: "Adjectives" },
  { id: "v173", ko: "건강하다", rom: "geonganghada", en: "to be healthy", ex: "저는 건강해요.", exEn: "I am healthy.", cat: "Adjectives" },
  { id: "v174", ko: "가방", rom: "gabang", en: "bag", ex: "가방이 무거워요.", exEn: "The bag is heavy.", cat: "Objects" },
  { id: "v175", ko: "연필", rom: "yeonpil", en: "pencil", ex: "연필로 써요.", exEn: "I write with a pencil.", cat: "Objects" },
  { id: "v176", ko: "펜", rom: "pen", en: "pen", ex: "펜을 빌려 주세요.", exEn: "Please lend me a pen.", cat: "Objects" },
  { id: "v177", ko: "공책", rom: "gongchaek", en: "notebook", ex: "공책에 이름을 써요.", exEn: "I write my name in the notebook.", cat: "Objects" },
  { id: "v178", ko: "의자", rom: "uija", en: "chair", ex: "의자에 앉아요.", exEn: "I sit on a chair.", cat: "Objects" },
  { id: "v179", ko: "책상", rom: "chaeksang", en: "desk", ex: "책상 위에 책이 있어요.", exEn: "There is a book on the desk.", cat: "Objects" },
  { id: "v180", ko: "문", rom: "mun", en: "door", ex: "문을 열어요.", exEn: "I open the door.", cat: "Objects" },
  { id: "v181", ko: "창문", rom: "changmun", en: "window", ex: "창문을 닫아요.", exEn: "I close the window.", cat: "Objects" },
  { id: "v182", ko: "휴대폰", rom: "hyudaepon", en: "mobile phone", ex: "휴대폰을 사용해요.", exEn: "I use a mobile phone.", cat: "Objects" },
  { id: "v183", ko: "열쇠", rom: "yeolsoe", en: "key", ex: "열쇠를 찾고 있어요.", exEn: "I am looking for the key.", cat: "Objects" },
  { id: "v184", ko: "우산", rom: "usan", en: "umbrella", ex: "비가 와서 우산을 써요.", exEn: "It is raining, so I use an umbrella.", cat: "Objects" },
  { id: "v185", ko: "시계", rom: "sigye", en: "clock / watch", ex: "시계를 봐요.", exEn: "I look at the clock.", cat: "Objects" },
  { id: "v186", ko: "안경", rom: "angyeong", en: "glasses", ex: "안경을 써요.", exEn: "I wear glasses.", cat: "Objects" },
  { id: "v187", ko: "지갑", rom: "jigap", en: "wallet", ex: "지갑을 잃어버렸어요.", exEn: "I lost my wallet.", cat: "Objects" },
  { id: "v188", ko: "사진기", rom: "sajingi", en: "camera", ex: "사진기로 사진을 찍어요.", exEn: "I take photos with a camera.", cat: "Objects" },
  { id: "v189", ko: "컵", rom: "keop", en: "cup", ex: "컵에 물이 있어요.", exEn: "There is water in the cup.", cat: "Objects" },
  { id: "v190", ko: "접시", rom: "jeopsi", en: "plate", ex: "접시에 음식을 담아요.", exEn: "I put food on the plate.", cat: "Objects" },
  { id: "v191", ko: "단어", rom: "daneo", en: "word", ex: "새 단어를 배워요.", exEn: "I learn a new word.", cat: "Language" },
  { id: "v192", ko: "문장", rom: "munjang", en: "sentence", ex: "문장을 읽어요.", exEn: "I read the sentence.", cat: "Language" },
  { id: "v193", ko: "문법", rom: "munbeop", en: "grammar", ex: "한국어 문법을 공부해요.", exEn: "I study Korean grammar.", cat: "Language" },
  { id: "v194", ko: "발음", rom: "bareum", en: "pronunciation", ex: "발음을 연습해요.", exEn: "I practice pronunciation.", cat: "Language" },
  { id: "v195", ko: "뜻", rom: "tteut", en: "meaning", ex: "이 단어의 뜻이 뭐예요?", exEn: "What does this word mean?", cat: "Language" },
  { id: "v196", ko: "질문", rom: "jilmun", en: "question", ex: "질문이 있어요.", exEn: "I have a question.", cat: "Language" },
  { id: "v197", ko: "대답", rom: "daedap", en: "answer", ex: "질문에 대답해요.", exEn: "I answer the question.", cat: "Language" },
  { id: "v198", ko: "말", rom: "mal", en: "speech / words", ex: "천천히 말해 주세요.", exEn: "Please speak slowly.", cat: "Language" },
  { id: "v199", ko: "이야기", rom: "iyagi", en: "story / conversation", ex: "친구와 이야기를 해요.", exEn: "I have a conversation with my friend.", cat: "Language" },
  { id: "v200", ko: "대화", rom: "daehwa", en: "conversation", ex: "한국어로 대화해요.", exEn: "I have a conversation in Korean.", cat: "Language" },
  { id: "v201", ko: "소리", rom: "sori", en: "sound", ex: "큰 소리가 들려요.", exEn: "I hear a loud sound.", cat: "Language" },
  { id: "v202", ko: "글", rom: "geul", en: "writing / text", ex: "글을 읽어요.", exEn: "I read the text.", cat: "Language" },
  { id: "v203", ko: "한국어로", rom: "hangugeoro", en: "in Korean", ex: "한국어로 말해 주세요.", exEn: "Please speak in Korean.", cat: "Language" },
  { id: "v204", ko: "영어로", rom: "yeongeoro", en: "in English", ex: "영어로 설명해 주세요.", exEn: "Please explain it in English.", cat: "Language" },
  { id: "v205", ko: "번역", rom: "beonyeok", en: "translation", ex: "이 문장을 번역해 주세요.", exEn: "Please translate this sentence.", cat: "Language" },
  { id: "v206", ko: "설명", rom: "seolmyeong", en: "explanation", ex: "문법을 설명해 주세요.", exEn: "Please explain the grammar.", cat: "Language" },
  { id: "v207", ko: "표현", rom: "pyohyeon", en: "expression / phrase", ex: "새로운 표현을 배웠어요.", exEn: "I learned a new expression.", cat: "Language" },
  { id: "v208", ko: "대화하다", rom: "daehwahada", en: "to converse", ex: "친구와 한국어로 대화해요.", exEn: "I converse with my friend in Korean.", cat: "Language" },
  { id: "v209", ko: "하늘", rom: "haneul", en: "sky", ex: "하늘이 맑아요.", exEn: "The sky is clear.", cat: "Nature" },
  { id: "v210", ko: "구름", rom: "gureum", en: "cloud", ex: "구름이 많아요.", exEn: "There are many clouds.", cat: "Nature" },
  { id: "v211", ko: "바람", rom: "baram", en: "wind", ex: "바람이 불어요.", exEn: "The wind is blowing.", cat: "Nature" },
  { id: "v212", ko: "해", rom: "hae", en: "sun", ex: "해가 떠요.", exEn: "The sun rises.", cat: "Nature" },
  { id: "v213", ko: "달빛", rom: "dalbit", en: "moonlight", ex: "달빛이 아름다워요.", exEn: "The moonlight is beautiful.", cat: "Nature" },
  { id: "v214", ko: "별", rom: "byeol", en: "star", ex: "밤에 별을 봐요.", exEn: "I see stars at night.", cat: "Nature" },
  { id: "v215", ko: "꽃", rom: "kkot", en: "flower", ex: "꽃이 예뻐요.", exEn: "The flower is pretty.", cat: "Nature" },
  { id: "v216", ko: "나무", rom: "namu", en: "tree", ex: "공원에 나무가 많아요.", exEn: "There are many trees in the park.", cat: "Nature" },
  { id: "v217", ko: "산", rom: "san", en: "mountain", ex: "주말에 산에 가요.", exEn: "I go to the mountain on the weekend.", cat: "Nature" },
  { id: "v218", ko: "바다", rom: "bada", en: "sea", ex: "여름에 바다에 가요.", exEn: "I go to the sea in summer.", cat: "Nature" },
  { id: "v219", ko: "강", rom: "gang", en: "river", ex: "강 옆을 걸어요.", exEn: "I walk beside the river.", cat: "Nature" },
  { id: "v220", ko: "호수", rom: "hosu", en: "lake", ex: "호수가 정말 아름다워요.", exEn: "The lake is really beautiful.", cat: "Nature" },
  { id: "v221", ko: "숲", rom: "sup", en: "forest", ex: "숲에서 산책해요.", exEn: "I take a walk in the forest.", cat: "Nature" },
  { id: "v222", ko: "꽃잎", rom: "kkotip", en: "flower petal", ex: "꽃잎이 떨어져요.", exEn: "Flower petals are falling.", cat: "Nature" },
  { id: "v223", ko: "번개", rom: "beongae", en: "lightning", ex: "번개가 쳐요.", exEn: "There is lightning.", cat: "Nature" },
  { id: "v224", ko: "천둥", rom: "cheondung", en: "thunder", ex: "천둥 소리가 커요.", exEn: "The sound of thunder is loud.", cat: "Nature" },
  { id: "v225", ko: "태풍", rom: "taepung", en: "typhoon", ex: "태풍이 오고 있어요.", exEn: "A typhoon is coming.", cat: "Nature" },
  { id: "v226", ko: "노래", rom: "norae", en: "song", ex: "좋아하는 노래를 들어요.", exEn: "I listen to my favorite song.", cat: "Entertainment" },
  { id: "v227", ko: "가수", rom: "gasu", en: "singer", ex: "그 가수를 좋아해요.", exEn: "I like that singer.", cat: "Entertainment" },
  { id: "v228", ko: "드라마", rom: "deurama", en: "drama / TV series", ex: "한국 드라마를 봐요.", exEn: "I watch Korean dramas.", cat: "Entertainment" },
  { id: "v229", ko: "게임", rom: "geim", en: "game", ex: "친구와 게임을 해요.", exEn: "I play games with my friend.", cat: "Entertainment" },
  { id: "v230", ko: "음악회", rom: "eumakhoe", en: "concert", ex: "주말에 음악회에 가요.", exEn: "I go to a concert on the weekend.", cat: "Entertainment" },
  { id: "v231", ko: "콘서트", rom: "konseoteu", en: "concert", ex: "콘서트에 가고 싶어요.", exEn: "I want to go to a concert.", cat: "Entertainment" },
  { id: "v232", ko: "배우", rom: "baeu", en: "actor / actress", ex: "그 배우가 유명해요.", exEn: "That actor is famous.", cat: "Entertainment" },
  { id: "v233", ko: "만화", rom: "manhwa", en: "comic", ex: "만화를 읽어요.", exEn: "I read comics.", cat: "Entertainment" },
  { id: "v234", ko: "웹툰", rom: "webtun", en: "webtoon", ex: "웹툰을 자주 봐요.", exEn: "I often read webtoons.", cat: "Entertainment" },
  { id: "v235", ko: "책장", rom: "chaekjang", en: "bookshelf", ex: "책장에 만화책이 있어요.", exEn: "There are comic books on the bookshelf.", cat: "Entertainment" },
  { id: "v236", ko: "춤", rom: "chum", en: "dance", ex: "춤을 배워요.", exEn: "I learn dance.", cat: "Entertainment" },
  { id: "v237", ko: "노래방", rom: "noraebang", en: "karaoke room", ex: "친구와 노래방에 가요.", exEn: "I go to karaoke with my friend.", cat: "Entertainment" },
  { id: "v238", ko: "공연", rom: "gongyeon", en: "performance", ex: "공연을 보러 가요.", exEn: "I go to see a performance.", cat: "Entertainment" },
  { id: "v239", ko: "관객", rom: "gwangaek", en: "audience member", ex: "관객이 많아요.", exEn: "There are many audience members.", cat: "Entertainment" },
  { id: "v240", ko: "취미", rom: "chwimi", en: "hobby", ex: "제 취미는 음악 감상이에요.", exEn: "My hobby is listening to music.", cat: "Entertainment" },
  { id: "v241", ko: "독서", rom: "dokseo", en: "reading", ex: "주말에 독서를 해요.", exEn: "I read on weekends.", cat: "Entertainment" },
  { id: "v242", ko: "미술", rom: "misul", en: "art", ex: "미술을 좋아해요.", exEn: "I like art.", cat: "Entertainment" },
  { id: "v243", ko: "그림", rom: "geurim", en: "drawing / picture", ex: "그림을 그려요.", exEn: "I draw a picture.", cat: "Entertainment" },
  { id: "v244", ko: "산책", rom: "sanchaek", en: "walk / stroll", ex: "공원에서 산책해요.", exEn: "I take a walk in the park.", cat: "Activities" },
  { id: "v245", ko: "쇼핑", rom: "syoping", en: "shopping", ex: "주말에 쇼핑해요.", exEn: "I go shopping on the weekend.", cat: "Activities" },
  { id: "v246", ko: "요리", rom: "yori", en: "cooking", ex: "요리를 좋아해요.", exEn: "I like cooking.", cat: "Activities" },
  { id: "v247", ko: "수영", rom: "suyeong", en: "swimming", ex: "여름에 수영을 해요.", exEn: "I swim in summer.", cat: "Activities" },
  { id: "v248", ko: "축구", rom: "chukgu", en: "soccer", ex: "친구와 축구를 해요.", exEn: "I play soccer with my friend.", cat: "Activities" },
  { id: "v249", ko: "농구", rom: "nonggu", en: "basketball", ex: "농구를 좋아해요.", exEn: "I like basketball.", cat: "Activities" },
  { id: "v250", ko: "달리기", rom: "dalligi", en: "running", ex: "아침에 달리기를 해요.", exEn: "I run in the morning.", cat: "Activities" },
  { id: "v251", ko: "등산", rom: "deungsan", en: "hiking", ex: "주말에 등산을 가요.", exEn: "I go hiking on the weekend.", cat: "Activities" },
  { id: "v252", ko: "캠핑", rom: "kaemping", en: "camping", ex: "여름에 캠핑을 가요.", exEn: "I go camping in summer.", cat: "Activities" },
  { id: "v253", ko: "사진 찍기", rom: "sajin jjikgi", en: "taking photos", ex: "여행하면서 사진 찍기를 좋아해요.", exEn: "I like taking photos while traveling.", cat: "Activities" },
  { id: "v254", ko: "청소", rom: "cheongso", en: "cleaning", ex: "아침에 방을 청소해요.", exEn: "I clean my room in the morning.", cat: "Activities" },
  { id: "v255", ko: "운전", rom: "unjeon", en: "driving", ex: "운전을 배워요.", exEn: "I learn to drive.", cat: "Activities" },
  { id: "v256", ko: "공부", rom: "gongbu", en: "study / studying", ex: "한국어 공부를 해요.", exEn: "I study Korean.", cat: "Activities" },
  { id: "v257", ko: "회의", rom: "hoeui", en: "meeting", ex: "오후에 회의가 있어요.", exEn: "I have a meeting in the afternoon.", cat: "Activities" },
  { id: "v258", ko: "준비", rom: "junbi", en: "preparation", ex: "시험을 준비해요.", exEn: "I prepare for the exam.", cat: "Activities" },
  { id: "v259", ko: "연습", rom: "yeonseup", en: "practice", ex: "매일 한국어를 연습해요.", exEn: "I practice Korean every day.", cat: "Activities" },
  { id: "v260", ko: "운동하기", rom: "undonghagi", en: "exercising", ex: "매일 운동하기를 좋아해요.", exEn: "I like exercising every day.", cat: "Activities" },
  { id: "v261", ko: "여가", rom: "yeoga", en: "leisure", ex: "여가 시간에 영화를 봐요.", exEn: "I watch movies during my leisure time.", cat: "Activities" },
  { id: "v262", ko: "컴퓨터", rom: "keompyuteo", en: "computer", ex: "컴퓨터로 공부해요.", exEn: "I study using a computer.", cat: "Software & Technology" },
  { id: "v263", ko: "프로그램", rom: "peurogeuraem", en: "program", ex: "새 프로그램을 만들어요.", exEn: "I make a new program.", cat: "Software & Technology" },
  { id: "v264", ko: "소프트웨어", rom: "sopeuteuweeo", en: "software", ex: "소프트웨어를 개발해요.", exEn: "I develop software.", cat: "Software & Technology" },
  { id: "v265", ko: "하드웨어", rom: "hadeuweeo", en: "hardware", ex: "하드웨어를 공부해요.", exEn: "I study hardware.", cat: "Software & Technology" },
  { id: "v266", ko: "코드", rom: "kodeu", en: "code", ex: "코드를 작성해요.", exEn: "I write code.", cat: "Software & Technology" },
  { id: "v267", ko: "코딩", rom: "koding", en: "coding", ex: "매일 코딩을 연습해요.", exEn: "I practice coding every day.", cat: "Software & Technology" },
  { id: "v268", ko: "개발", rom: "gaebal", en: "development", ex: "소프트웨어 개발을 공부해요.", exEn: "I study software development.", cat: "Software & Technology" },
  { id: "v269", ko: "개발자", rom: "gaebalja", en: "developer", ex: "저는 소프트웨어 개발자가 되고 싶어요.", exEn: "I want to become a software developer.", cat: "Software & Technology" },
  { id: "v270", ko: "웹사이트", rom: "websaiteu", en: "website", ex: "웹사이트를 만들어요.", exEn: "I make a website.", cat: "Software & Technology" },
  { id: "v271", ko: "인터넷", rom: "inteonet", en: "internet", ex: "인터넷을 사용해요.", exEn: "I use the internet.", cat: "Software & Technology" },
  { id: "v272", ko: "데이터", rom: "deiteo", en: "data", ex: "데이터를 분석해요.", exEn: "I analyze data.", cat: "Software & Technology" },
  { id: "v273", ko: "서버", rom: "seobeo", en: "server", ex: "서버에 데이터를 저장해요.", exEn: "I store data on the server.", cat: "Software & Technology" },
  { id: "v274", ko: "파일", rom: "pail", en: "file", ex: "파일을 저장해요.", exEn: "I save the file.", cat: "Software & Technology" },
  { id: "v275", ko: "폴더", rom: "poldeo", en: "folder", ex: "새 폴더를 만들어요.", exEn: "I create a new folder.", cat: "Software & Technology" },
  { id: "v276", ko: "앱", rom: "aep", en: "app", ex: "새 앱을 다운로드했어요.", exEn: "I downloaded a new app.", cat: "Software & Technology" },
  { id: "v277", ko: "다운로드", rom: "dauneullodeu", en: "download", ex: "파일을 다운로드해요.", exEn: "I download the file.", cat: "Software & Technology" },
  { id: "v278", ko: "업데이트", rom: "eopdeiteu", en: "update", ex: "프로그램을 업데이트해요.", exEn: "I update the program.", cat: "Software & Technology" },
  { id: "v279", ko: "비밀번호", rom: "bimilbeonho", en: "password", ex: "비밀번호를 입력하세요.", exEn: "Please enter your password.", cat: "Software & Technology" },
  { id: "v280", ko: "로그인", rom: "rogeuin", en: "login", ex: "웹사이트에 로그인해요.", exEn: "I log in to the website.", cat: "Software & Technology" },
  { id: "v281", ko: "버그", rom: "beogeu", en: "bug", ex: "프로그램에서 버그를 찾았어요.", exEn: "I found a bug in the program.", cat: "Software & Technology" },
];

/* Grammar library */
const GRAMMAR = [
  {
    id: "g1", level: "Beginner", pattern: "은/는 (topic marker)",
    meaning: "marks the topic of a sentence",
    explanation: "은/는 introduces what the sentence is about. Use 는 after a vowel, 은 after a consonant.",
    examples: [
      { ko: "저는 학생이에요.", en: "I am a student." },
      { ko: "이것은 책이에요.", en: "This is a book." },
    ],
    practice: { type: "fill", prompt: "저___ 한국 사람이에요.", answer: "는", options: ["은", "는", "이", "가"] },
  },
  {
    id: "g2", level: "Beginner", pattern: "이/가 (subject marker)",
    meaning: "marks the grammatical subject",
    explanation: "이/가 highlights the subject doing the action or being described. 가 after a vowel, 이 after a consonant.",
    examples: [
      { ko: "날씨가 좋아요.", en: "The weather is good." },
      { ko: "이름이 뭐예요?", en: "What is your name?" },
    ],
    practice: { type: "fill", prompt: "친구___ 와요.", answer: "가", options: ["가", "이", "은", "를"] },
  },
  {
    id: "g3", level: "Beginner", pattern: "을/를 (object marker)",
    meaning: "marks the object of a verb",
    explanation: "을/를 marks what receives the action. 를 after a vowel, 을 after a consonant.",
    examples: [
      { ko: "밥을 먹어요.", en: "I eat rice." },
      { ko: "책을 읽어요.", en: "I read a book." },
    ],
    practice: { type: "fill", prompt: "물___ 마셔요.", answer: "을", options: ["를", "을", "가", "은"] },
  },
  {
    id: "g4", level: "Beginner", pattern: "~아요/어요/해요",
    meaning: "polite present tense ending",
    explanation: "The everyday polite speech ending. Use 아요 after ㅏ/ㅗ stems, 어요 otherwise, 해요 for 하다 verbs.",
    examples: [
      { ko: "가요.", en: "I go. (polite)" },
      { ko: "먹어요.", en: "I eat. (polite)" },
    ],
    practice: { type: "mc", prompt: "'먹다' in polite present tense is:", answer: "먹어요", options: ["먹어요", "먹아요", "먹해요", "먹다요"] },
  },
  {
    id: "g5", level: "Intermediate", pattern: "~고 싶다",
    meaning: "want to do something",
    explanation: "Attach 고 싶다 to a verb stem to express desire to do that action.",
    examples: [
      { ko: "한국에 가고 싶어요.", en: "I want to go to Korea." },
      { ko: "커피를 마시고 싶어요.", en: "I want to drink coffee." },
    ],
    practice: { type: "mc", prompt: "'want to eat' is:", answer: "먹고 싶어요", options: ["먹고 싶어요", "먹어 싶어요", "먹으고 싶다", "먹다 싶어요"] },
  },
  {
    id: "g6", level: "Intermediate", pattern: "~(으)ㄴ 후에",
    meaning: "after doing something",
    explanation: "Attached to a verb stem to indicate that an action happens after another finishes.",
    examples: [
      { ko: "숙제를 한 후에 자요.", en: "I sleep after doing homework." },
      { ko: "먹은 후에 이를 닦아요.", en: "I brush my teeth after eating." },
    ],
    practice: { type: "mc", prompt: "'after eating' is:", answer: "먹은 후에", options: ["먹은 후에", "먹고 후에", "먹기 후에", "먹으 후에"] },
  },
  {
    id: "g7", level: "Intermediate", pattern: "~(으)면",
    meaning: "if / when",
    explanation: "A conditional connector attached to a verb or adjective stem meaning 'if' or 'when'.",
    examples: [
      { ko: "시간이 있으면 만나요.", en: "If I have time, let's meet." },
      { ko: "비가 오면 집에 있어요.", en: "If it rains, I stay home." },
    ],
    practice: { type: "mc", prompt: "'if you go' is:", answer: "가면", options: ["가면", "가서", "가고", "간면"] },
  },
  {
    id: "g8", level: "Formal", pattern: "~습니다/ㅂ니다",
    meaning: "formal present tense ending",
    explanation: "Used in formal, official, or news contexts. More formal than 아요/어요.",
    examples: [
      { ko: "감사합니다.", en: "Thank you. (formal)" },
      { ko: "여기 있습니다.", en: "Here it is. (formal)" },
    ],
    practice: { type: "mc", prompt: "Formal version of '가요' is:", answer: "갑니다", options: ["갑니다", "가습니다", "가ㅂ니다", "가답니다"] },
  },

  /* Additional Grammar */

  {
    id: "g9", level: "Beginner", pattern: "에 (location / destination)",
    meaning: "marks a destination, location, or specific time",
    explanation: "에 is commonly used after a place to show where someone goes or is, and after a time expression.",
    examples: [
      { ko: "학교에 가요.", en: "I go to school." },
      { ko: "집에 있어요.", en: "I am at home." },
    ],
    practice: { type: "fill", prompt: "학교___ 가요.", answer: "에", options: ["에", "에서", "을", "는"] },
  },
  {
    id: "g10", level: "Beginner", pattern: "에서 (place of action)",
    meaning: "marks the place where an action occurs",
    explanation: "에서 is used after a location where an activity or action takes place.",
    examples: [
      { ko: "학교에서 공부해요.", en: "I study at school." },
      { ko: "공원에서 운동해요.", en: "I exercise at the park." },
    ],
    practice: { type: "fill", prompt: "도서관___ 책을 읽어요.", answer: "에서", options: ["에서", "에", "을", "가"] },
  },
  {
    id: "g11", level: "Beginner", pattern: "도 (also / too)",
    meaning: "means also, too, or as well",
    explanation: "도 replaces particles such as 은/는, 이/가, and 을/를 when expressing the meaning 'also' or 'too'.",
    examples: [
      { ko: "저도 학생이에요.", en: "I am also a student." },
      { ko: "커피도 마셔요.", en: "I also drink coffee." },
    ],
    practice: { type: "fill", prompt: "저___ 한국어를 공부해요. (also)", answer: "도", options: ["도", "는", "가", "를"] },
  },
  {
    id: "g12", level: "Beginner", pattern: "와/과, 하고, (이)랑",
    meaning: "and / with",
    explanation: "These forms can connect nouns or express doing something with someone. 와/과 is more formal, while 하고 and 이랑/랑 are common in conversation.",
    examples: [
      { ko: "친구와 영화를 봐요.", en: "I watch a movie with a friend." },
      { ko: "밥하고 김치를 먹어요.", en: "I eat rice and kimchi." },
    ],
    practice: { type: "mc", prompt: "Which can mean 'with a friend'?", answer: "친구와", options: ["친구와", "친구를", "친구가", "친구에"] },
  },
  {
    id: "g13", level: "Beginner", pattern: "있다 / 없다",
    meaning: "to have / exist and to not have / not exist",
    explanation: "있다 expresses existence or possession, while 없다 expresses non-existence or lack of something.",
    examples: [
      { ko: "시간이 있어요.", en: "I have time." },
      { ko: "돈이 없어요.", en: "I don't have money." },
    ],
    practice: { type: "mc", prompt: "'I don't have time' is:", answer: "시간이 없어요.", options: ["시간이 없어요.", "시간이 있어요.", "시간을 없어요.", "시간은 가요."] },
  },
  {
    id: "g14", level: "Beginner", pattern: "안 + Verb/Adjective",
    meaning: "simple negation",
    explanation: "Place 안 before a verb or adjective to make a simple negative statement.",
    examples: [
      { ko: "학교에 안 가요.", en: "I don't go to school." },
      { ko: "커피를 안 마셔요.", en: "I don't drink coffee." },
    ],
    practice: { type: "fill", prompt: "저는 커피를 ___ 마셔요.", answer: "안", options: ["안", "못", "도", "더"] },
  },
  {
    id: "g15", level: "Beginner", pattern: "못 + Verb",
    meaning: "cannot / be unable to",
    explanation: "못 is placed before a verb to express inability or inability due to circumstances.",
    examples: [
      { ko: "한국어를 못 해요.", en: "I can't speak Korean." },
      { ko: "오늘 못 가요.", en: "I can't go today." },
    ],
    practice: { type: "mc", prompt: "'I can't go today' is:", answer: "오늘 못 가요.", options: ["오늘 못 가요.", "오늘 안 가요.", "오늘도 가요.", "오늘 가고 싶어요."] },
  },
  {
    id: "g16", level: "Intermediate", pattern: "~아/어서",
    meaning: "because / so / and then",
    explanation: "아/어서 connects related clauses and can express a reason, result, or sequence of actions.",
    examples: [
      { ko: "배가 아파서 병원에 가요.", en: "My stomach hurts, so I go to the hospital." },
      { ko: "집에 와서 숙제를 해요.", en: "I come home and then do homework." },
    ],
    practice: { type: "mc", prompt: "'because I am tired' is:", answer: "피곤해서", options: ["피곤해서", "피곤하면", "피곤하지만", "피곤하고"] },
  },
  {
    id: "g17", level: "Intermediate", pattern: "~지만",
    meaning: "but / although",
    explanation: "지만 connects two contrasting ideas and can be translated as 'but' or 'although'.",
    examples: [
      { ko: "비가 오지만 학교에 가요.", en: "It is raining, but I go to school." },
      { ko: "작지만 예뻐요.", en: "It is small, but pretty." },
    ],
    practice: { type: "fill", prompt: "비가 오___ 학교에 가요.", answer: "지만", options: ["지만", "고", "면", "서"] },
  },
  {
    id: "g18", level: "Intermediate", pattern: "~기 때문에",
    meaning: "because / due to",
    explanation: "기 때문에 gives a clear reason for an action or situation. It is common in writing and more formal explanations.",
    examples: [
      { ko: "비가 오기 때문에 집에 있어요.", en: "I stay home because it is raining." },
      { ko: "시험이 있기 때문에 공부해요.", en: "I study because I have an exam." },
    ],
    practice: { type: "mc", prompt: "'because I have an exam' is:", answer: "시험이 있기 때문에", options: ["시험이 있기 때문에", "시험이 있으면", "시험이 있지만", "시험이 있고"] },
  },
  {
    id: "g19", level: "Intermediate", pattern: "~(으)ㄹ 수 있다/없다",
    meaning: "can / cannot",
    explanation: "This pattern expresses ability or possibility. Use 을 수 after a consonant and ㄹ 수 after a vowel.",
    examples: [
      { ko: "한국어를 읽을 수 있어요.", en: "I can read Korean." },
      { ko: "오늘 만날 수 없어요.", en: "I cannot meet today." },
    ],
    practice: { type: "mc", prompt: "'I can go' is:", answer: "갈 수 있어요", options: ["갈 수 있어요", "가고 싶어요", "가야 해요", "가면 돼요"] },
  },
  {
    id: "g20", level: "Intermediate", pattern: "~아/어야 하다",
    meaning: "must / have to",
    explanation: "This grammar pattern expresses obligation or necessity, meaning that someone must or has to do something.",
    examples: [
      { ko: "숙제를 해야 해요.", en: "I have to do my homework." },
      { ko: "학교에 가야 해요.", en: "I have to go to school." },
    ],
    practice: { type: "mc", prompt: "'I have to study' is:", answer: "공부해야 해요", options: ["공부해야 해요", "공부하고 싶어요", "공부할 수 있어요", "공부하지 않아요"] },
  },
];

/* Learning path sections */
const PATH = [
  {
    section: "Foundation",
    units: [
      { id: "u_hangul", title: "Hangul", icon: "가", lessonIds: ["l1"] },
      { id: "u_basicvocab", title: "Basic Vocabulary", icon: "📚", lessonIds: ["l2"] },
      { id: "u_greetings", title: "Greetings", icon: "🙏", lessonIds: ["l3"] },
      { id: "u_numbers", title: "Numbers", icon: "🔢", lessonIds: ["l4"] },
      { id: "u_sentence", title: "Basic Sentence Structure", icon: "📐", lessonIds: ["l5"] },
    ],
  },
  {
    section: "Beginner Korean",
    units: [
      { id: "u_particles", title: "Particles", icon: "🔗", lessonIds: ["l6"] },
      { id: "u_verbconj", title: "Verb Conjugation", icon: "🔄", lessonIds: ["l7"] },
      { id: "u_daily", title: "Daily Activities", icon: "☀️", lessonIds: ["l8"] },
      { id: "u_time", title: "Time & Dates", icon: "🕐", lessonIds: ["l9"] },
      { id: "u_places", title: "Places & Directions", icon: "🗺️", lessonIds: ["l10"] },
    ],
  },
  {
    section: "Intermediate Korean",
    units: [
      { id: "u_intgram", title: "Intermediate Grammar", icon: "🧩", lessonIds: ["l11"] },
      { id: "u_formal", title: "Formal Speech", icon: "🎩", lessonIds: ["l12"] },
      { id: "u_connect", title: "Connecting Sentences", icon: "➰", lessonIds: ["l13"] },
      { id: "u_reading", title: "Reading Practice", icon: "📰", lessonIds: ["l14"] },
      { id: "u_listening", title: "Listening Practice", icon: "🎧", lessonIds: ["l15"] },
    ],
  },
  {
    section: "TOPIK Preparation",
    units: [
      { id: "u_topikvocab", title: "Vocabulary", icon: "🈺", lessonIds: ["l16"] },
      { id: "u_topikread", title: "Reading", icon: "📖", lessonIds: ["l17"] },
      { id: "u_topiklisten", title: "Listening", icon: "🔊", lessonIds: ["l18"] },
      { id: "u_topikwrite", title: "Writing", icon: "✍️", lessonIds: ["l19"] },
      { id: "u_topikmock", title: "Mock Questions", icon: "🧪", lessonIds: ["l20"] },
    ],
  },
];

/* Full lesson definitions — at least 3 complete with rich question variety */
const LESSONS = {
  l1: {
    id: "l1", title: "Hangul Basics", unit: "u_hangul", xp: 20,
    vocabIds: ["v16"],
    questions: [
      { type: "mc", prompt: "Which letter makes the 'ㅁ' sound (like 'm')?", options: ["ㅁ", "ㄴ", "ㅅ", "ㄹ"], answer: "ㅁ" },
      { type: "mc", prompt: "What does 가 represent?", options: ["ga", "na", "da", "ma"], answer: "ga" },
      { type: "translate_ko_en", prompt: "이름", answer: "name" },
      { type: "fill", prompt: "저는 ___이에요. (name)", answer: "이름", options: ["이름", "학교", "친구", "사람"] },
      { type: "match", prompt: "Match the Hangul to its romanization", pairs: [["가", "ga"], ["나", "na"], ["다", "da"], ["라", "ra"]] },
    ],
  },
  l2: {
    id: "l2", title: "Everyday Objects", unit: "u_basicvocab", xp: 20,
    vocabIds: ["v10", "v19", "v20", "v18"],
    questions: [
      { type: "translate_ko_en", prompt: "책", answer: "book" },
      { type: "translate_en_ko", prompt: "coffee", answer: "커피", options: ["커피", "물", "밥", "책"] },
      { type: "mc", prompt: "'집' means:", options: ["house", "school", "friend", "money"], answer: "house" },
      { type: "fill", prompt: "저는 ___에 있어요. (home)", answer: "집", options: ["집", "책", "돈", "커피"] },
      { type: "match", prompt: "Match the word to its meaning", pairs: [["책", "book"], ["돈", "money"], ["집", "house"], ["커피", "coffee"]] },
    ],
  },
  l3: {
    id: "l3", title: "First Greetings", unit: "u_greetings", xp: 25,
    vocabIds: ["v2", "v3", "v6"],
    questions: [
      { type: "translate_ko_en", prompt: "안녕하세요", answer: "hello" },
      { type: "translate_en_ko", prompt: "thank you", answer: "감사합니다", options: ["감사합니다", "안녕하세요", "친구", "사람"] },
      { type: "mc", prompt: "How do you politely say 'hello'?", options: ["안녕하세요", "감사합니다", "친구", "이름"], answer: "안녕하세요" },
      { type: "arrange", prompt: "Arrange to form: 'Nice to meet you, friend.'", words: ["친구야,", "만나서", "반가워요"], answer: "친구야, 만나서 반가워요" },
      { type: "listening", prompt: "Listen and choose what you hear", audioText: "감사합니다", options: ["감사합니다", "안녕하세요", "죄송합니다", "괜찮아요"], answer: "감사합니다" },
    ],
  },
  l4: {
    id: "l4", title: "Counting in Korean", unit: "u_numbers", xp: 20,
    vocabIds: ["v8", "v9"],
    questions: [
      { type: "mc", prompt: "'하나' means:", options: ["one", "two", "three", "four"], answer: "one" },
      { type: "translate_en_ko", prompt: "two", answer: "둘", options: ["하나", "둘", "셋", "넷"] },
      { type: "fill", prompt: "사과 ___ 주세요. (one)", answer: "하나", options: ["하나", "둘", "셋", "넷"] },
      { type: "match", prompt: "Match numbers to Hangul", pairs: [["1", "하나"], ["2", "둘"], ["3", "셋"], ["4", "넷"]] },
    ],
  },
  l5: {
    id: "l5", title: "Simple Sentences", unit: "u_sentence", xp: 25,
    vocabIds: ["v1", "v14"],
    questions: [
      { type: "arrange", prompt: "Arrange to form: 'I go to school.'", words: ["저는", "학교에", "가요"], answer: "저는 학교에 가요" },
      { type: "fill", prompt: "저는 학교___ 가요. (to)", answer: "에", options: ["에", "가", "을", "는"] },
      { type: "translate_ko_en", prompt: "저는 학교에 가요.", answer: "I go to school." },
      { type: "mc", prompt: "Basic Korean sentence order is:", options: ["Subject-Object-Verb", "Subject-Verb-Object", "Verb-Subject-Object", "Object-Verb-Subject"], answer: "Subject-Object-Verb" },
    ],
  },
  l6: {
    id: "l6", title: "Particles in Action", unit: "u_particles", xp: 25,
    vocabIds: ["v7", "v11"],
    questions: [
      { type: "fill", prompt: "친구___ 와요. (subject)", answer: "가", options: ["가", "을", "는", "에"] },
      { type: "fill", prompt: "물___ 마셔요. (object)", answer: "을", options: ["을", "가", "는", "에서"] },
      { type: "mc", prompt: "은/는 is used to mark:", options: ["topic", "object", "location", "time"], answer: "topic" },
      { type: "translate_en_ko", prompt: "today", answer: "오늘", options: ["오늘", "내일", "지금", "어제"] },
    ],
  },
  l7: {
    id: "l7", title: "Conjugating Verbs", unit: "u_verbconj", xp: 25,
    vocabIds: ["v13", "v14", "v15"],
    questions: [
      { type: "mc", prompt: "Polite present of '가다' (to go) is:", options: ["가요", "가아요", "가해요", "간요"], answer: "가요" },
      { type: "fill", prompt: "저는 사과를 ___. (eat, polite)", answer: "먹어요", options: ["먹어요", "먹아요", "먹해요", "먹다요"] },
      { type: "translate_ko_en", prompt: "날씨가 좋아요.", answer: "The weather is good." },
      { type: "listening", prompt: "Listen and choose what you hear", audioText: "먹어요", options: ["먹어요", "가요", "좋아요", "와요"], answer: "먹어요" },
    ],
  },
  l8: {
    id: "l8", title: "My Daily Routine", unit: "u_daily", xp: 25,
    vocabIds: ["v5", "v13"],
    questions: [
      { type: "arrange", prompt: "Arrange: 'I ate a meal.'", words: ["저는", "밥을", "먹었어요"], answer: "저는 밥을 먹었어요" },
      { type: "reading", prompt: "저는 아침에 밥을 먹어요. 그리고 학교에 가요.", question: "What does the person do in the morning first?", options: ["Eats a meal", "Goes to school", "Drinks coffee", "Reads a book"], answer: "Eats a meal" },
      { type: "mc", prompt: "'먹었어요' means:", options: ["ate (past)", "eat (present)", "will eat (future)", "eating"], answer: "ate (past)" },
    ],
  },
  l9: {
    id: "l9", title: "Talking About Time", unit: "u_time", xp: 25,
    vocabIds: ["v11", "v12", "v17"],
    questions: [
      { type: "translate_en_ko", prompt: "tomorrow", answer: "내일", options: ["내일", "오늘", "어제", "시간"] },
      { type: "fill", prompt: "___ 만나요. (tomorrow)", answer: "내일", options: ["내일", "오늘", "친구", "학교"] },
      { type: "mc", prompt: "'시간이 없어요' means:", options: ["I don't have time", "I have time", "I like time", "Time is good"], answer: "I don't have time" },
    ],
  },
  l10: {
    id: "l10", title: "Finding Your Way", unit: "u_places", xp: 25,
    vocabIds: ["v1", "v10"],
    questions: [
      { type: "reading", prompt: "학교 옆에 집이 있어요.", question: "Where is the house?", options: ["Next to the school", "Inside the school", "Far from the school", "Behind the coffee shop"], answer: "Next to the school" },
      { type: "translate_ko_en", prompt: "학교가 어디예요?", answer: "Where is the school?" },
      { type: "mc", prompt: "'옆' means:", options: ["next to", "far", "inside", "behind"], answer: "next to" },
    ],
  },
  l11: {
    id: "l11", title: "Expressing Desire", unit: "u_intgram", xp: 30,
    vocabIds: [],
    questions: [
      { type: "mc", prompt: "'~고 싶다' expresses:", options: ["wanting to do something", "having done something", "being able to do something", "not wanting to do something"], answer: "wanting to do something" },
      { type: "fill", prompt: "한국에 가___ 싶어요. (want to go)", answer: "고", options: ["고", "면", "서", "은"] },
      { type: "translate_en_ko", prompt: "I want to eat", answer: "먹고 싶어요", options: ["먹고 싶어요", "먹어 싶어요", "먹다 싶어요", "먹으 싶어요"] },
    ],
  },
  l12: {
    id: "l12", title: "Speaking Formally", unit: "u_formal", xp: 30,
    vocabIds: [],
    questions: [
      { type: "mc", prompt: "Formal version of '가요' (go) is:", options: ["갑니다", "가습니다", "가답니다", "가ㅂ습니다"], answer: "갑니다" },
      { type: "translate_ko_en", prompt: "여기 있습니다.", answer: "Here it is." },
      { type: "fill", prompt: "감사___. (formal thank you)", answer: "합니다", options: ["합니다", "해요", "하고", "한다"] },
    ],
  },
  l13: {
    id: "l13", title: "Connecting Ideas", unit: "u_connect", xp: 30,
    vocabIds: [],
    questions: [
      { type: "mc", prompt: "'~(으)면' means:", options: ["if / when", "after", "because", "but"], answer: "if / when" },
      { type: "fill", prompt: "비가 ___ 집에 있어요. (if it rains)", answer: "오면", options: ["오면", "오고", "온 후에", "오지만"] },
      { type: "arrange", prompt: "Arrange: 'If I have time, let's meet.'", words: ["시간이", "있으면,", "만나요"], answer: "시간이 있으면, 만나요" },
    ],
  },
  l14: {
    id: "l14", title: "Reading a Short Note", unit: "u_reading", xp: 30,
    vocabIds: [],
    questions: [
      { type: "reading", prompt: "민수: 오늘 시간 있어요? 저녁에 만나고 싶어요.\n지나: 네, 좋아요! 7시에 만나요.", question: "What do Minsu and Jina agree to do?", options: ["Meet at 7", "Meet tomorrow", "Study together", "Eat lunch"], answer: "Meet at 7" },
      { type: "translate_ko_en", prompt: "저녁에 만나고 싶어요.", answer: "I want to meet in the evening." },
      { type: "mc", prompt: "'좋아요!' in this context expresses:", options: ["agreement", "disagreement", "confusion", "apology"], answer: "agreement" },
    ],
  },
  l15: {
    id: "l15", title: "Listening in Context", unit: "u_listening", xp: 30,
    vocabIds: [],
    questions: [
      { type: "listening", prompt: "Listen and choose what you hear", audioText: "오늘 시간 있어요?", options: ["오늘 시간 있어요?", "내일 시간 있어요?", "오늘 뭐 해요?", "오늘 어디 가요?"], answer: "오늘 시간 있어요?" },
      { type: "listening", prompt: "Listen and choose what you hear", audioText: "7시에 만나요.", options: ["7시에 만나요.", "8시에 만나요.", "7시에 가요.", "7시에 먹어요."], answer: "7시에 만나요." },
      { type: "mc", prompt: "'시에' is used with:", options: ["clock time", "dates", "places", "people"], answer: "clock time" },
    ],
  },
  l16: {
    id: "l16", title: "TOPIK Vocabulary I", unit: "u_topikvocab", xp: 30,
    vocabIds: [],
    questions: [
      { type: "mc", prompt: "'경험' means:", options: ["experience", "environment", "exercise", "example"], answer: "experience" },
      { type: "translate_ko_en", prompt: "노력하다", answer: "to make an effort" },
      { type: "fill", prompt: "저는 매일 한국어를 ___. (study, polite)", answer: "공부해요", options: ["공부해요", "공부하다", "공부했다", "공부할"] },
    ],
  },
  l17: {
    id: "l17", title: "TOPIK Reading I", unit: "u_topikread", xp: 30,
    vocabIds: [],
    questions: [
      { type: "reading", prompt: "저는 매일 아침 공원에서 운동을 합니다. 운동을 하면 기분이 좋아집니다.", question: "Why does the writer feel good?", options: ["Because of exercising", "Because of eating", "Because of sleeping", "Because of studying"], answer: "Because of exercising" },
      { type: "mc", prompt: "(Practice question, not an official TOPIK item) '기분이 좋아지다' means:", options: ["mood improves", "mood worsens", "gets tired", "gets hungry"], answer: "mood improves" },
    ],
  },
  l18: {
    id: "l18", title: "TOPIK Listening I", unit: "u_topiklisten", xp: 30,
    vocabIds: [],
    questions: [
      { type: "listening", prompt: "Listen and choose what you hear (practice item)", audioText: "공원에서 운동을 해요.", options: ["공원에서 운동을 해요.", "학교에서 공부를 해요.", "집에서 쉬어요.", "식당에서 밥을 먹어요."], answer: "공원에서 운동을 해요." },
    ],
  },
  l19: {
    id: "l19", title: "TOPIK Writing Basics", unit: "u_topikwrite", xp: 30,
    vocabIds: [],
    questions: [
      { type: "arrange", prompt: "Arrange (practice item): 'I exercise at the park every morning.'", words: ["저는", "매일", "아침에", "공원에서", "운동을", "합니다"], answer: "저는 매일 아침에 공원에서 운동을 합니다" },
      { type: "fill", prompt: "(practice item) 운동을 ___ 기분이 좋아져요. (if I exercise)", answer: "하면", options: ["하면", "하고", "한 후에", "하지만"] },
    ],
  },
  l20: {
    id: "l20", title: "TOPIK Mock Set", unit: "u_topikmock", xp: 40,
    vocabIds: [],
    questions: [
      { type: "reading", prompt: "(practice item) 어제는 비가 왔지만 오늘은 날씨가 좋습니다.", question: "How was the weather yesterday?", options: ["It rained", "It was sunny", "It snowed", "It was windy"], answer: "It rained" },
      { type: "listening", prompt: "Listen (practice item) and choose what you hear", audioText: "오늘 날씨가 좋습니다.", options: ["오늘 날씨가 좋습니다.", "오늘 날씨가 나쁩니다.", "어제 비가 왔습니다.", "내일 눈이 옵니다."], answer: "오늘 날씨가 좋습니다." },
      { type: "mc", prompt: "(practice item) '~지만' means:", options: ["but", "and", "because", "if"], answer: "but" },
    ],
  },
};

/* TOPIK practice sets (clearly original/practice material) */
const TOPIK_SETS = [
  { id: "t1", level: "TOPIK I", skill: "Reading", lessonId: "l17" },
  { id: "t2", level: "TOPIK I", skill: "Listening", lessonId: "l18" },
  { id: "t3", level: "TOPIK II", skill: "Writing", lessonId: "l19" },
  { id: "t4", level: "TOPIK II", skill: "Mock Set", lessonId: "l20" },
];

function levelFromXP(xp) {
  const perLevel = 100;
  const level = Math.floor(xp / perLevel) + 1;
  const into = xp % perLevel;
  return { level, into, need: perLevel };
    }
